=== jcbrother/LuAppUIAutomation/cases-suite/lu-uia-suite.dtd
<!--
Here is a quick overview of the main parts of this DTD.
1. It's for uia test suite definition.
2. Test engineers just have to design test suites according to this DTD, and run it directly by executing engine. 
-->


<!-- A suite is the top-level element of a lu-uia-test.xml -->
<!ELEMENT suite (cases) >
<!-- Attributes description: 
@attr name             test suite name.
@attr description      test suite description.
-->
<!ATTLIST suite 
    name CDATA #REQUIRED
    description CDATA #REQUIRED
>


<!ELEMENT cases (before-test-cases, test-cases, after-test-cases) >
<!-- Attributes description: 
@attr exec-before-test   execute BeforeTestCases suite or not, true for yes , false for not.
@attr exec-after-test    execute AfterTestCases suite or not , true for yes , fasle for not.
-->
<!ATTLIST cases 
    exec-before-test (true | false) "true"
        exec-before-test CDATA #REQUIRED
    exec-after-test (true | false) "true"
        exec-after-test CDATA #REQUIRED
>


<!ELEMENT before-test-cases (case) >
<!-- Attributes description: 
@attr purpose           test purpose. 
@attr preserve-order    keep xml file defined execution order. if false, execute case order by id.
-->
<!ATTLIST before-test-cases 
    purpose CDATA #REQUIRED
    preserve-order (true | false) "true"
        preserve-order CDATA #REQUIRED
>


<!ELEMENT test-cases (case) >
<!-- Attributes description: 
@attr purpose           test purpose. 
@attr preserve-order    keep xml file defined case execution order. if false, execute case order by id.
-->
<!ATTLIST test-cases 
    purpose CDATA #REQUIRED
    preserve-order (true | false) "true"
        preserve-order CDATA #REQUIRED
>


<!ELEMENT after-test-cases (case) >
<!-- Attributes description: 
@attr purpose           test purpose. 
@attr preserve-order    keep xml file defined execution order. if false, execute case order by id.
-->
<!ATTLIST after-test-cases 
    purpose CDATA #REQUIRED
    preserve-order (true | false) "true"
        preserve-order CDATA #REQUIRED
>


<!ELEMENT case (step)* >
<!-- Attributes description: 
@attr id          case execution order key.  
@attr title       case title. 
@attr priority    case priority.
-->
<!ATTLIST case
    id CDATA #REQUIRED
    title CDATA #REQUIRED
    priority CDATA #REQUIRED
>


<!ELEMENT step ( method-param | assert-key)* >
<!-- Attributes description: 
@attr id                step execution order key.
@attr src-page-name     current page name.
@attr method            operation method like swipe ,tap ,slide-up etc.
@attr dest-page-name    destination page after method executed.
@attr snapshoot         snapshoot or not after executed method.
@attr step-desc         step descriptions.
-->
<!ATTLIST step
    id CDATA #REQUIRED
    src-page-name CDATA #REQUIRED
    method (swipeUp|swipeDown|swipeLeft|swipeRight|swipeForBack|shortTapById|longTapById|shortTapByXpath|longTapByXpath|sendKeysById|sendKeysByXpath) "shortTypeById"
        method CDATA #REQUIRED
    dest-page-name CDATA #REQUIRED
    snapshoot  (true | false) "false"
        snapshoot CDATA #REQUIRED
    step-desc CDATA #REQUIRED
>


<!ELEMENT assert-key ANY >
<!-- Attributes description: 
@attr value              element id or xpath etc.
@attr location-type      locate element by id or
@attr compare-type       define comparing type
@attr compare-value      assert by something from data source or static source.
-->
<!ATTLIST assert-key
    value CDATA #REQUIRED
    location-type ( id | xpath )  "id"
        location-type CDATA #REQUIRED
    compare-type ( equal | not-equal | visible | invisible ) "equal"
        compare-type CDATA #REQUIRED
    compare-value CDATA #IMPLIED
>


<!ELEMENT method-param ANY >
<!-- Attributes description: 
@attr name     parameter name
@attr type     parameter type
@attr value    parameter value  
-->
<!ATTLIST method-param
    name (elemId | elemXpath | keyStr) "elemId"
        name CDATA #REQUIRED
    type (element-id | element-xpath | input-string) "id"
        type CDATA #REQUIRED
    value CDATA #REQUIRED
>

=== jcbrother/LuAppUIAutomation/cases-suite/ji_jin_search.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE suite SYSTEM "lu-uia-suite.dtd" >
<suite name="JiJinSearch" description="基金搜索测试用例集">
    <cases exec-before-test="true" exec-after-test="true">
        <before-test-cases purpose="测试前准备" preserve-order="true">
            <case id="" title="" priority="">
                <step id="" src-page-name="" method="" dest-page-name="" snapshoot="true" step-desc="" >
                    <method-param name="" type="element-id" value="" />
                    <assert-key value="" location-type="xpath" compare-value="sqlMapId:*/jetjiang" />
                </step>
            </case>
        </before-test-cases>

        <test-cases purpose="测试基金搜索功能" preserve-order="true">
            <case id="" title="" priority="">
                <step id="" src-page-name="" method="" dest-page-name="" snapshoot="true" step-desc="" >
                    <method-param name="" type="element-id" value="" />
                    <assert-key value="" location-type="xpath"  compare-value=""/>
                </step>
            </case>
        </test-cases>

        <after-test-cases purpose="测试清理" preserve-order="true">
            <case id="" title="" priority="">
                <step id="" src-page-name="" method="" dest-page-name="" snapshoot="true" step-desc="" >
                    <method-param name="" type="element-id" value="" />
                    <assert-key value="" location-type="id" compare-value="" />
                </step>
            </case>
        </after-test-cases>
    </cases>
</suite>

=== jcbrother/LuAppUIAutomation/cases-suite/test.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE suite SYSTEM "lu-uia-suite.dtd" >
<suite name="Test" description="测试用例集">
    <cases exec-before-test="false" exec-after-test="false">
        <before-test-cases purpose="测试前准备" preserve-order="true">
            <case id="1" title="测试前用例一" priority="2">
                <step id="1" src-page-name="测试前页面1" method="shortTapById" dest-page-name="测试前页面3" snapshoot="true" step-desc="滑动启动图至最后一页" >
                    <assert-key value="立即体验按钮" location-type="id" compare-value="sqlMapId:*/jetjiang" />
                </step>
                <step id="2" src-page-name="测试前页面3" method="shortTapById" dest-page-name="测试前页面4" snapshoot="true" step-desc="进陆金所APP首页" >
                    <method-param name="elemId" type="element-id" value="com.lufax.android://tsx1" />
                    <assert-key value="com.lufax.android://tsv1" location-type="id" compare-value="sqlMapId:*/jetjiang1" />
                </step>
            </case>
        </before-test-cases>

        <test-cases purpose="测试基金搜索功能" preserve-order="true">
            <case id="2" title="进投资理财列表页" priority="1">
                <step id="1" src-page-name="MainPage" method="testPrint1" dest-page-name="JiJinInFinancePage" snapshoot="true" step-desc="点击投资理财，进投资理财列表页" >
                    <method-param name="param1" value="helloworldofprint1" />
                    <method-param name="param2" value="2"></method-param>
                    <method-param name="param3" value="3"></method-param>
                    <assert-key value="com.lufax.android://tsv2" location-type="xpath"  compare-value="sqlMapId:*/jetjiang2"/>
                </step>
                <step id="2" src-page-name="MainPage" method="testPrint2" dest-page-name="JiJinInFinancePage" snapshoot="true" step-desc="点击基金，进投资理财基金列表页" >
                    <method-param name="param1" value="helloworldofprint2" />
                    <method-param name="param2" value="2"></method-param>
                    <method-param name="param3" value="3"></method-param>
                    <assert-key value="com.lufax.android://tsv3" location-type="xpath"  compare-value="sqlMapId:*/jetjiang3"/>
                </step>
            </case>
            <case id="1" title="进投资理财列表页" priority="1">
                <step id="1" src-page-name="MainPage" method="testPrint3" dest-page-name="JiJinInFinancePage" snapshoot="true" step-desc="点击投资理财，进投资理财列表页" >
                    <method-param name="param1" value="1" />
                    <method-param name="param2" value="2"></method-param>
                    <method-param name="param3" value="helloworldofprint3"></method-param>
                    <assert-key value="com.lufax.android://tsv2" location-type="xpath"  compare-value="sqlMapId:*/jetjiang2"/>
                </step>
                <step id="2" src-page-name="MainPage" method="testPrint4" dest-page-name="JiJinInFinancePage" snapshoot="true" step-desc="点击基金，进投资理财基金列表页" >
                    <method-param name="param1" value="1" />
                    <method-param name="param2" value="helloworldofprint4"></method-param>
                    <method-param name="param3" value="3"></method-param>
                    <assert-key value="com.lufax.android://tsv3" location-type="xpath"  compare-value="sqlMapId:*/jetjiang3"/>
                </step>
            </case>
        </test-cases>

        <after-test-cases purpose="测试后清理" preserve-order="true">
            <case id="1" title="关闭appium driver" priority="2">
                <step id="1" src-page-name="基金搜索结果页" method="shortTapById" dest-page-name="手机桌面" snapshoot="true" step-desc="关闭appium driver" >
                    <assert-key value="com.lufax.android://tsv5" location-type="id" compare-value="桌面" />
                </step>
            </case>
        </after-test-cases>
    </cases>
</suite>
